---
html_document: default
author: "Brea Koenes"
date: "2/16/2022"
title: "Plotly Graphics"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
require(plotly)
```

```{r load-data}
races <- read_csv("data/races.csv")
status <- read_csv("data/status.csv")
results <- read_csv("data/results.csv", col_types = cols(number = col_character()))
```

```{r join datasets}
joined_results <- left_join(status, results, by='statusId') %>%
                left_join(races, results, by='raceId')
```

```{r Wrangling}
status_data <- joined_results %>%
  mutate(status = if_else((status == "Accident") |
                          (status == "Mechanical"),
                          "Accident/Mechanical",
                          status)) %>%                  # Mutate new a new category
  filter(status == "Accident/Mechanical" |
         status == "Finished") %>%                      # Filter 2 categories
  group_by(status, year) %>% 
  summarise(status_sum = n())
```

```{r Visual}
fig <- plot_ly(status_data, 
               x = ~year, 
               y = ~status_sum, 
               type = 'scatter', 
               mode = 'lines'
               ) %>% 
  add_annotations(
  xref="paper",
  yref="paper",
  x=.89,
  y=0.13,
  text="Accidents/Mechanical Failures"
  ) %>%
  add_annotations(
  xref="paper",
  yref="paper",
  x=0.98,
  y=0.73,
  text="Finished"
  ) %>% 
  layout(title = "Finished vs. Failure Results of F1 Race Entries",
         xaxis = list(title = "Year"),
         yaxis = list (title = "Race Entries"))
fig
```



